On postinst DB upgrade fail, warn user about disclosure of MySQL credentials

diff --git a/debian/bluecherry.postinst b/debian/bluecherry.postinst
--- a/debian/bluecherry.postinst
+++ b/debian/bluecherry.postinst
@@ -9,7 +9,7 @@ DB_BACKUP_GZ_FILE=/tmp/bc_db.sql.gz
 function db_upgrade_err() {
 	trap - ERR # avoid recurrence
 	# Say something to user
-	echo "An error occurred while migrating your database to the latest version. Please contact Bluecherry support here: https://bluecherry.zendesk.com/anonymous_requests/new . Provide full  uncut output from console (the above text)." >&2
+	echo -e "An error occurred while migrating your database to the latest version. Please contact Bluecherry support here: https://bluecherry.zendesk.com/anonymous_requests/new . Provide full  uncut output from console (the above text).\n\nATTENTION! The above log contains your MySQL logins and passwords, please do not post these logs on public forums.\n" >&2
 	if [[ -e $DB_BACKUP_GZ_FILE ]]
 	then
 		echo "Restoring DB from previously taken backup in $DB_BACKUP_GZ_FILE" >&2
