DB upgrading rework
Drop the usage of dbconfig-common, which ended up with some DB
patches being not applied in some cases.
Add strict control of DB schema being exactly the same the service
expects.
Since now, DB schema as numeric version, which is stored in
GlobalSettings table by parameter = 'G_DB_VERSION'. Version 2.2 release
has G_DB_VERSION = 2020000 (2.02.00.00).
Make all tables use UTF-8 for strings.

diff --git a/debian/bluecherry.postinst b/debian/bluecherry.postinst
--- a/debian/bluecherry.postinst
+++ b/debian/bluecherry.postinst
@@ -1,15 +1,39 @@
-#!/bin/sh -e
+#!/bin/bash -e
+
+set -x # trace
 
 . /usr/share/debconf/confmodule
-. /usr/share/dbconfig-common/dpkg/postinst.mysql
 
+DB_BACKUP_GZ_FILE=/tmp/bc_db.sql.gz
 
-dbc_generate_include_args="-o template_infile=/usr/share/bluecherry/bluecherry.conf.in"
-dbc_generate_include=template:/etc/bluecherry.conf
-dbc_generate_include_perms=0640
-dbc_generate_include_owner=bluecherry:bluecherry
+function create_tables_write_version() {
+	# Env vars $dbname, $user, $password are exported from calling script
+	# Attention: always use them with quoted, to handle correctly spaces inside them.
+	mysql -u"$user" -p"$password" -D"$dbname" < /usr/share/bluecherry/schema_mysql.sql
+	# Save actual DB version
+	DB_VERSION=`cat /usr/share/bluecherry/installed_db_version`
+	echo "INSERT INTO GlobalSettings (parameter, value) VALUES ('G_DB_VERSION', '$DB_VERSION')" | mysql -u"$user" -p"$password" -D"$dbname"
+}
 
-dbc_go bluecherry $@
+function db_upgrade_err() {
+	trap - ERR # avoid recurrence
+	# Say something to user
+	echo "Some error happened during DB upgrade" >&2
+	if [[ -e $DB_BACKUP_GZ_FILE ]]
+	then
+		echo "Restoring DB from previously taken backup in $DB_BACKUP_GZ_FILE" >&2
+		# Drop all tables
+		for x in `echo "show tables" | mysql -D"$dbname" -u"$user" -p"$password" | tail -n +2`
+		do
+			echo "SET FOREIGN_KEY_CHECKS=0; DROP TABLE $x" | mysql -D"$dbname" -u"$user" -p"$password"
+		done
+		echo "SET FOREIGN_KEY_CHECKS=1" | mysql -D"$dbname" -u"$user" -p"$password" # Restore setting just in case
+
+		# Restore from backup
+		gunzip -c $DB_BACKUP_GZ_FILE | mysql -D"$dbname" -u"$user" -p"$password"
+	fi
+	exit 1 # Indicate failure
+}
 
 case "$1" in
 	configure|reconfigure)
@@ -58,6 +82,136 @@ case "$1" in
 		if [ -x /sbin/apparmor_parser ]; then
 			: #apparmor_parser -r < /etc/apparmor.d/usr.sbin.bc-server || true
 		fi
+
+		# Manage DB
+
+		trap db_upgrade_err ERR # will restore DB from backup and terminate the execution with failure retcode
+
+		if ! [[ -s /etc/bluecherry.conf ]]
+		then
+			# 0-bytes config - fresh installation
+			# Create DB
+			# Ask questions
+			db_input high bluecherry/mysql_admin_login
+			db_input high bluecherry/mysql_admin_password
+			db_input high bluecherry/db_name
+			db_input high bluecherry/db_user
+			db_input high bluecherry/db_password
+			db_go
+
+			db_get bluecherry/mysql_admin_login
+			export MYSQL_ADMIN_LOGIN="$RET"
+			db_get bluecherry/mysql_admin_password
+			export MYSQL_ADMIN_PASSWORD="$RET"
+			db_get bluecherry/db_name
+			export dbname="$RET"
+			db_get bluecherry/db_user
+			export user="$RET"
+			db_get bluecherry/db_password
+			export password="$RET"
+
+			# Actually create DB and tables
+			echo "CREATE DATABASE $dbname" | mysql -u"$MYSQL_ADMIN_LOGIN" -p"$MYSQL_ADMIN_PASSWORD"
+			echo "GRANT ALL ON ${dbname}.* to ${user}@'localhost' IDENTIFIED BY '$password'" | mysql -u"$MYSQL_ADMIN_LOGIN" -p"$MYSQL_ADMIN_PASSWORD"
+
+			create_tables_write_version
+			# Put initial data into DB
+			mysql -u"$user" -p"$password" -D"$dbname" < /usr/share/bluecherry/initial_data_mysql.sql
+
+			# Generate config
+			cat /usr/share/bluecherry/bluecherry.conf.in | sed -e "s/_DBC_DBNAME_/${dbname}/"  -e "s/_DBC_DBUSER_/${user}/"  -e "s/_DBC_DBPASS_/${password}/" > /etc/bluecherry.conf
+
+		else
+			# Upgrade
+			# Parse config for DB credentials
+			TMP=`mktemp`
+			egrep '(dbname|user|password)' /etc/bluecherry.conf | sed 's/ = /=/' > $TMP
+			source $TMP
+			rm $TMP
+			export dbname user password
+
+			# Get DB version
+			DB_VERSION=`echo "SELECT value from GlobalSettings WHERE parameter = 'G_DB_VERSION'" | mysql -D"$dbname" -u"$user" -p"$password" | tail -n 1`
+
+			if [[ "$DB_VERSION" != "`cat /usr/share/bluecherry/installed_db_version`" ]]
+			then
+
+				# Notify user through debconf non-blocking dialog that backup is taken
+				echo "Going to updgrade Bluecherry DB. Taking a backup into $DB_BACKUP_GZ_FILE just in case" >&2
+				# Backup the DB
+				mysqldump "$dbname" -u"$user" -p"$password" | gzip -c > $DB_BACKUP_GZ_FILE
+
+				if [[ "$DB_VERSION" == "" ]]
+				then
+					# If no version stored (pre-2.2 was installed):
+					# Rename all tables to ${table}_bkp
+					for x in `echo "show tables" | mysql -D"$dbname" -u"$user" -p"$password" | tail -n +2`
+					do
+						echo "RENAME TABLE $x TO ${x}_bkp" | mysql -D"$dbname" -u"$user" -p"$password"
+					done
+					# Create tables from the reference DB schema
+					create_tables_write_version
+
+					# Migrate data from all tables
+					# Devices.rtsp_rtp_prefer_tcp, added in 2.1.7-7. Workaround for twofold incoherences:
+					# 1) Failure of dbconfig-common to apply a DB patch to add it
+					# 2) Different fields order in fresh installation and patched one
+					# Try to add, ignore result because this may fail if field is already here
+					echo "ALTER TABLE Devices_bkp ADD COLUMN rtsp_rtp_prefer_tcp boolean NOT NULL DEFAULT 1 AFTER rtsp_password" | mysql -D"$dbname" -u"$user" -p"$password" || true
+					# Try to move it to be after rtsp_password for the case it was added in the end
+					echo "ALTER TABLE Devices_bkp MODIFY COLUMN rtsp_rtp_prefer_tcp boolean NOT NULL DEFAULT 1 AFTER rtsp_password" | mysql -D"$dbname" -u"$user" -p"$password"
+					# Now table contents copying should work
+
+					# All other tables columns modifications (besides of constraints) are from 2.0.0 days, those versions are not used as of present days (May 2014)
+					# preinst checks that version is not less than 2.0.3
+
+					for x_bkp in `echo "show tables" | mysql -D"$dbname" -u"$user" -p"$password" | tail -n +2 | grep _bkp`
+					do
+						x=`echo $x_bkp | sed 's/_bkp//'`
+						echo "SET FOREIGN_KEY_CHECKS=0; INSERT INTO $x SELECT * FROM $x_bkp" | mysql -D"$dbname" -u"$user" -p"$password"
+						# Drop all *_bkp tables
+						echo "SET FOREIGN_KEY_CHECKS=0; DROP TABLE $x_bkp" | mysql -D"$dbname" -u"$user" -p"$password"
+						echo "SET FOREIGN_KEY_CHECKS=1" | mysql -D"$dbname" -u"$user" -p"$password" # Restore setting just in case
+					done
+
+				else
+					# If there is a DB version stored (2.2 and newer was installed):
+					pushd /usr/share/bluecherry/mysql-upgrade
+					# Note that entries must be numeric, and they are traversed in numeric order, ascending
+					# Entries are directories, see below
+					for x in `ls | sort -n`
+					do
+						if [[ $x -gt $DB_VERSION ]]
+						then
+							pushd $x
+								# We execute each *.sh script, in lexicographical order
+								for y in *.sh
+								do
+									# Such shell scenraio can make some checks and execute some SQL statements.
+									# DB credentials are exported by env vars $dbname, $user, $password for them
+									./$y
+								done
+							popd
+						fi
+						DB_VERSION=$x # our DB_VERSION is updated
+					done
+					popd
+
+					# A check
+					if [[ "`cat /usr/share/bluecherry/installed_db_version`" != "$DB_VERSION" ]]
+					then
+						false # Fail the installation
+					fi
+
+					# Save new DB_VERSION
+					echo "UPDATE GlobalSettings SET value='$DB_VERSION' WHERE parameter = 'G_DB_VERSION'" | mysql -D"$dbname" -u"$user" -p"$password"
+				fi # Whether there was non-empty DB_VERSION
+			fi # Whether old and new DB version match
+		fi # Whether there was an upgrade or fresh install
+		/usr/share/bluecherry/compare.sh >&2
+		trap - ERR
+
+		# End of DB management
 
 		;;
 esac
