debian: preinst: Abort if bc-services user already exists

diff --git a/debian/bluecherry.preinst b/debian/bluecherry.preinst
--- a/debian/bluecherry.preinst
+++ b/debian/bluecherry.preinst
@@ -18,6 +18,9 @@ case "$1" in
 				-U -G audio,video -M -U -r bc-services
 			# And www-data will need it too
 			usermod -a -G video,audio,bc-services,dialout www-data
+		else
+			echo "Error: bc-services user already exists!"
+			exit 1
 		fi
 		if which service >/dev/null 2>&1; then
 			service bluecherry stop || true
